### ISSUE TITLE
Where the occlusion, crowding and size benchmarks has been used

### ISSUE THREAD

**Issue by yw155** [matteorr/coco-analyze#1]
Hi @matteorr ,

Thanks for your great work.

I ran the codes successfully. But I don't know where the occlusion, crowding and size benchmarks has been used. Could you tell me directly?

Thank you.

Ying

**Comment by matteorr** [comment]
Hi @yw155 , you can download the benchmarks for occlusion, crowding and size from the main [project page.](http://www.vision.caltech.edu/~mronchi/projects/PoseErrorDiagnosis/#resources). Let me know if you have any follow-up questions.
