### ISSUE TITLE
Missing figures within the generated latex file

### ISSUE THREAD

**Issue by Vaufreyd** [matteorr/coco-analyze#10]
Hello,

Another issue from my side. Each time, one figure contains only empty filenames (example below). Even running your fake example. To give you some context, at the very beginning of the script, I have an error "failed to get the current screen resources". I use the script on a remote computer using x2go that may explain this error and *may* explain also the missing images (??)

If I can help to test something, please let me know.

Thank you. Doms.

\begin{figure}[h!]
\centering
\resizebox{\linewidth}{!}{
\begin{tabular}{cc|cc}
\hline\hline
\textbf{High Score - Low OKS} & \textbf{Low Score - High OKS} & \textbf{High Score - Low OKS} & \textbf{Low Score - High OKS}\\
\hline
\includegraphics[width=.2\linewidth,height=.15\paperwidth,keepaspectratio]{} &
\includegraphics[width=.2\linewidth,height=.15\paperwidth,keepaspectratio]{} &
\includegraphics[width=.2\linewidth,height=.15\paperwidth,keepaspectratio]{} &
\includegraphics[width=.2\linewidth,height=.15\paperwidth,keepaspectratio]{}\\
\includegraphics[width=.2\linewidth,height=.15\paperwidth,keepaspectratio]{} &
\includegraphics[width=.2\linewidth,height=.15\paperwidth,keepaspectratio]{} &
\includegraphics[width=.2\linewidth,height=.15\paperwidth,keepaspectratio]{} &
\includegraphics[width=.2\linewidth,height=.15\paperwidth,keepaspectratio]{}\\
\includegraphics[width=.2\linewidth,height=.15\paperwidth,keepaspectratio]{} &
\includegraphics[width=.2\linewidth,height=.15\paperwidth,keepaspectratio]{} &
\includegraphics[width=.2\linewidth,height=.15\paperwidth,keepaspectratio]{} &
\includegraphics[width=.2\linewidth,height=.15\paperwidth,keepaspectratio]{}\\
\includegraphics[width=.2\linewidth,height=.15\paperwidth,keepaspectratio]{} &
\includegraphics[width=.2\linewidth,height=.15\paperwidth,keepaspectratio]{} &
\includegraphics[width=.2\linewidth,height=.15\paperwidth,keepaspectratio]{} &
\includegraphics[width=.2\linewidth,height=.15\paperwidth,keepaspectratio]{}\\
\includegraphics[width=.2\linewidth,height=.15\paperwidth,keepaspectratio]{} &
\includegraphics[width=.2\linewidth,height=.15\paperwidth,keepaspectratio]{} &
\includegraphics[width=.2\linewidth,height=.15\paperwidth,keepaspectratio]{} &
\includegraphics[width=.2\linewidth,height=.15\paperwidth,keepaspectratio]{}\\
\includegraphics[width=.2\linewidth,height=.15\paperwidth,keepaspectratio]{} &
\includegraphics[width=.2\linewidth,height=.15\paperwidth,keepaspectratio]{} &
\includegraphics[width=.2\linewidth,height=.15\paperwidth,keepaspectratio]{} &
\includegraphics[width=.2\linewidth,height=.15\paperwidth,keepaspectratio]{}\\
\end{tabular}
}
\vspace{-3mm}
\caption{ {\small \textbf{Top Scoring Errors.} Scoring errors ordered by relevance top to bottom and left to right.
Each scoring error consists of a ground-truth annotation and a pair of detections shown side by side, one with high score and low OKS (left),
and one with low score and high OKS (right).
The relevance is computed as the geometric mean between the difference of the OKS obtained
by the two detections and the difference of their confidence score.
The ground truth skeleton is in green, and the color coding of the detection skeleton is described in Sec. 1.
Each image title contains the following information:
[detection\textunderscore score, OKS, image\textunderscore id, ground\textunderscore truth\textunderscore id, detection\textunderscore id].}}
\end{figure}

**Comment by matteorr** [comment]
I haven't tested this code to work remotely, so I can't help you much on this. Closing the issue, please reopen if you have other questions or if you solved it and would like to share the solution. Thanks!

**Comment by matteorr** [comment]
@Vaufreyd - I just noticed that if your detections have less than 12 scoring errors Fig.9 in the report will have some empty paths, just like you observed. So I fixed that with this [commit](https://github.com/matteorr/coco-analyze/commit/5d00c259c6fc08a5a6b63649aadf8ee085ae6710).

However, the code still cannot generate a figure in which there are less than 12 scoring errors without raising an empty path error.

**Comment by Vaufreyd** [comment]
@matteorr, sorry for answering so late. I just restart my experimentations. With the last version from git, there are still, as you said, empty figures. I understand that these figures could be empty, but the latex file is not compiling. I will try to propose something and get back to you.
