### ISSUE TITLE
Error analysis for object detection

### ISSUE THREAD

**Issue by mmderakhshani** [matteorr/coco-analyze#11]
Hi,
Thanks for your great repository.

I have got a question. I would like to have the same error analysis for object detection task. Is there a way to have the same output for detection annotation with your implementation?

Appreciating you in advance for any responses.

**Comment by netanel-s** [comment]
+1,
Would like to know as well.
Thanks in advance!

**Comment by matteorr** [comment]
Sorry for the late reply @mmderakhshani , @netanel-s. Right now there is a [matlab function in the cocoapi repo](https://github.com/cocodataset/cocoapi/blob/master/MatlabAPI/CocoEval.m#L57-L67) that will analyze your detections in the style of [Derek Hoiem's error analysis on object detection](http://dhoiem.cs.illinois.edu/publications/eccv2012_detanalysis_derek.pdf).

There isn't an immediate plan to port this repo to object detection, but if you post requests on the [coco-api repo](https://github.com/cocodataset/cocoapi) and enough people ask for it things might change.

**Comment by LaCandela** [comment]
+1
This is interesting to me as well! :)

**Comment by nimakasipour** [comment]
+1

**Comment by matteorr** [comment]
You can take a look at this tool, it might be of interest: https://dbolya.github.io/tide/
