### ISSUE TITLE
Assertion Error for Pose Estimation in COCO Validation 2017  

### ISSUE THREAD

**Issue by FJR-Nancy** [matteorr/coco-analyze#12]
Hello,
Thanks for your great repository. However, I have got an assertion error while running the code for human pose estimation in COCO Validation 2017. I have attached the error as follows.
![image](https://user-images.githubusercontent.com/7094092/39298934-1ec81ed4-497a-11e8-9265-bce0d6be1713.png)

Thanks for any responses.

**Comment by ahangchen** [comment]
I think this analyzing code is writen for coco2014, so when you run for coco2017, erros is inevitable. But I'm also looking forward to a analyzing code for coco2017.

**Comment by matteorr** [comment]
@FJR-Nancy, @ahangchen - I was able to run the evaluation and analysis code on COCOval2017 with the keypoint detections from issue #14 without getting the assertion error. So I cannot replicate your problem. 

Do you still get the assertion error? If so, can you share your keypoint detections so I can try determine if it's a bug in my code or in your detections?

**Comment by matteorr** [comment]
Closing this issue since I cannot replicate the error. **Code works on COCOval2017**. Feel free to reopen if there are any updates.
