### ISSUE TITLE
Replacing attribute 'set_axis_bgcolor' with 'set_facecolor'

### ISSUE THREAD

**Issue by yw155** [matteorr/coco-analyze#13]
Hi @matteorr, thanks for your great work. When I run the tool, I meet a problem that 'AxesSubplot' object has no attribute 'set_axis_bgcolor' in the file of 'scoringErrors.py'. I noticed that this attribute is already replaced by 'set_facecolor'. So it is better to update this attribute in multiple scripts. Thanks.

**Comment by matteorr** [comment]
Addressed! Thanks for catching this.
