### ISSUE TITLE
OPt Score

### ISSUE THREAD

**Issue by nitba** [matteorr/coco-analyze#18]
Hi @matteorr 

Thank you so much for your great analysis,
Would you please explain more about opt.score , It seems confusing for me, would you please clear the steps for that?

Thanks

**Comment by matteorr** [comment]
@Ivamcoder  - Thanks for your question! Could you please be a bit more specific about what part you find confusing? Is it the overall definition, or something about the code?

Sec. 3.2 in the [paper](http://www.vision.caltech.edu/~mronchi/projects/PoseErrorDiagnosis/#cite) should clarify why scoring errors are important, and how I measure them.
