### ISSUE TITLE
about Python 2 and 3 compatibility(unicode issue)

### ISSUE THREAD

**Issue by mvdelt** [matteorr/coco-analyze#23]
Hi,
in the commit e87a451904c30c57c2769a7ce5477d4539055dda ,
the compatibility issue and the solution(unicode->bytes) was suggested,
but I think the code(pycocotools/coco.py) revised back again(bytes->unicode). 
Is there any reason?

**Comment by matteorr** [comment]
Thanks for pointing that out. Fixed with commit 9eb8a0a9e57ad1e592661efc2b8964864c0e6f28
