### ISSUE TITLE
2D bounding box analysis?

### ISSUE THREAD

**Issue by LaCandela** [matteorr/coco-analyze#27]
Is there a way to use this api for the analysisi of 2D bounding box detections?

**Comment by nimakasipour** [comment]
I am looking for it too! but it seems it works just for "keypoints" 
analyze() function for python is not also merged to cocoEval ! https://github.com/cocodataset/cocoapi/issues/167

**Comment by matteorr** [comment]
This analysis was not designed for 2D bounding boxes but exclusively for multi-instance keypoint analysis. Take a look at this for bounding boxes: https://dbolya.github.io/tide/
