### ISSUE TITLE
coco_url no longer work

### ISSUE THREAD

**Issue by jeffffffli** [matteorr/coco-analyze#4]
The `coco_url` of images have changed, format `http://mscoco.org/images/IMAGEID` doesn't work anymore. 
The new annotations file are updated on http://cocodataset.org/#download. In the new annotations, the `coco_url` are changed. 
I think the annotation file in this repository and the url  format in the analysisAPI should be updated.

**Comment by matteorr** [comment]
[New commit](https://github.com/matteorr/coco-analyze/commit/19428e6f6776b3e5e1868e37c509c9bfb675fd44) takes care of that. Thanks for pointing that out!
