### ISSUE TITLE
Key error raised when running code.

### ISSUE THREAD

**Issue by GongXinyuu** [matteorr/coco-analyze#6]
Hi, thanks to your great code. However, I've encountered an error when running your code.

> ...
Analyzing background false positives and false negatives...
<mrr:2.0>Running per image evaluation...
<mrr:2.0>Evaluate annotation type *keypoints*
<mrr:2.0>DONE (t=3.76s).
DONE (t=4.53s).
/Users/gxy/coco/PythonAPI/analysisAPI/backgroundFalseNegErrors.py:215: MatplotlibDeprecationWarning: The set_axis_bgcolor function was deprecated in version 2.0. Use set_facecolor instead.
  ax.set_axis_bgcolor('lightgray')
/Users/gxy/coco/PythonAPI/analysisAPI/backgroundFalseNegErrors.py:226: MatplotlibDeprecationWarning: The set_axis_bgcolor function was deprecated in version 2.0. Use set_facecolor instead.
  ax.set_axis_bgcolor('lightgray')
Traceback (most recent call last):
  File "/Users/gxy/coco/PythonAPI/run_analysis.py", line 138, in <module>
    main()
  File "/Users/gxy/coco/PythonAPI/run_analysis.py", line 126, in main
    paths = occlusionAndCrowdingSensitivity( coco_analyze, .75, saveDir )
  File "/Users/gxy/coco/PythonAPI/analysisAPI/occlusionAndCrowdingSensitivity.py", line 49, in occlusionAndCrowdingSensitivity
    total_gts += overlap_index[no]
KeyError: 7
Process finished with exit code 1

Could you please help me?

**Comment by GongXinyuu** [comment]
Besides, I've also found that the generated performance report lacks the Fig 9. Top Scoring Errors.

**Comment by mkocabas** [comment]
Hi @GloryDream, I got same error as you. Did you solve the issue?

**Comment by GongXinyuu** [comment]
@mkocabas nope, I just comment the relevant lines to run the code.

**Comment by mkocabas** [comment]
I have added `if no in overlap_index:` before this [line](https://github.com/matteorr/coco-analyze/blob/e7deb0e83448648e45728b6825b1c9f02b5408f4/analysisAPI/occlusionAndCrowdingSensitivity.py#L49)

**Comment by GongXinyuu** [comment]
@mkocabas Hi, does this solve the problem?

**Comment by mkocabas** [comment]
Yes, it solved and doesn't affect the output as far as I see.

**Comment by GongXinyuu** [comment]
@mkocabas Thank U very much!

**Comment by matteorr** [comment]
Duplicate of [issue #5](https://github.com/matteorr/coco-analyze/issues/5), addressed in [this commit](https://github.com/matteorr/coco-analyze/commit/6f108aeb8fe0f6bd25d25be6c5450ef1155a1e07)
