### ISSUE TITLE
how to get the _results.json

### ISSUE THREAD

**Issue by Ai-is-light** [matteorr/coco-analyze#8]

**Comment by matteorr** [comment]
- Please provide more details. 
- Check the COCO website: [link1](http://cocodataset.org/#format), [link2](http://cocodataset.org/#keypoints-eval).

**Comment by ouceduxzk** [comment]
I am also confused, i generated my .json file and then run the demo, but the AP50 and other are so low , below 0.05, which is confusing, since the model I used is good for sure, does the 'score' matters in the calcualtion, to me, I think score is calcuated by coco api
