### ISSUE TITLE
Special characters in team name

### ISSUE THREAD

**Issue by Vaufreyd** [matteorr/coco-analyze#9]
Hello,

First, thanks for sharing your great code with the community.

My issue: If I put some specific characters (like '_') in the team name, the generated tex won't compile with a "Miss inserted $" error. Solution could be to parse the team name for such specific characters and generate their latex counterparts ("\_" in this case).

Thank you. Doms.

**Comment by matteorr** [comment]
Hi Doms,

Thanks for pointing this out. As you can see [here](https://github.com/matteorr/coco-analyze/blob/release/run_analysis.py#L38) I replaced the `_` in the annotation names with the escape character for `latex`, but forgot to do the same for the team name and version number. 

Based on your suggestion and this [link](https://tex.stackexchange.com/questions/48632/underscores-in-words-text) I updated the latex template to deal with special characters directly in `latex` without having to intercept them in python.

You can see the edits in this [commit](https://github.com/matteorr/coco-analyze/commit/28f4b72c911b8162e488db4c9ae781de2f1398ab).

Should work now.
